image:
    file: .gitpod.Dockerfile
tasks:
- name: install gfastats rdeval kreeq
  command: |
    cd /workspace
    #gfastats
    wget https://github.com/vgl-hub/gfastats/releases/download/v1.3.7/gfastats.v1.3.7-linux.zip
    unzip gfastats.v1.3.7-linux.zip
    chmod a+x ./gfastats
    #kreeq
    wget https://github.com/vgl-hub/kreeq/releases/download/v0.0.1/kreeq.v0.0.1-linux.zip
    unzip kreeq.v0.0.1-linux.zip
    chmod a+x ./kreeq
    export PATH=/workspace:$PATH
    #rdeval
    micromamba install bioconda::htslib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/gitpod/micromamba/lib/
    git clone https://github.com/vgl-hub/rdeval --recursive
    cd rdeval
    make -j CFLAGS="-I/home/gitpod/micromamba/include/ -L/home/gitpod/micromamba/lib/"
    mv build/bin/rdeval ..
    cd ..
    #large data
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/large_input.fasta.gz
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/filtered.fastq
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/filtered2.fastq
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/input.fa

workspaceLocation: "/workspace"
